version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  slack: circleci/slack@4.3.0
commands:
    notify-slack:
        description: "Send Slack notification"
        parameters:
            emoji:
                type: string
                default: ""
            event_type:
                type: string
                default: "pass"
            success_failed:
                type: string
                default: ""
        steps:
            - slack/notify:
                  event: << parameters.event_type >>
                  channel: circleci-builds
                  custom: |
                      {
                        "text": "CircleCI Job",              
                        "blocks": [
                          {
                            "type": "header",
                            "text": {
                              "type": "plain_text",
                              "text": "Deploy << parameters.success_failed >> << parameters.emoji >>",
                              "emoji": true
                            }
                          },
                          {
                            "type": "section",
                            "fields": [
                              {
                                "type": "mrkdwn",
                                "text": "*Project*: $CIRCLE_PROJECT_REPONAME\n*Branch*: $CIRCLE_BRANCH"
                              }
                            ]
                          },
                          {
                            "type": "actions",
                            "elements": [
                              {
                                "type": "button",
                                "text": {
                                  "type": "plain_text",
                                  "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                              }
                            ]
                          }
                        ]
                      }
jobs:
  deploy_staging:
    description: Deploy application to Google Kubernetes Engine in Staging Environment
    machine: true
    resource_class: viral-solutions-llc/self-host
    steps:
      - checkout
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: sample-cluster
          gcloud-service-key: GCLOUD_SERVICE_KEY_STAGING
          google-compute-zone: GOOGLE_COMPUTE_ZONE_STAGING
          google-project-id: GOOGLE_PROJECT_ID_STAGING
          perform-login: true
      - run:
          name: Install gcloud dependies & Connect to Cluster 
          command: |
            gcloud components update
            gcloud components install gke-gcloud-auth-plugin
            export USE_GKE_GCLOUD_AUTH_PLUGIN=True
            gcloud container clusters get-credentials dev-dtuc-cluster
      - run:
          name: Deploy  and Upgrade Application 
          command: | 
            helm upgrade <release name> --install ./deployment-infrastructure/(application_name) -n dtuc -f ./deployment-infrastructure/vs-uc-api/values.yaml
      - notify-slack:
          event_type: "pass"
          success_failed: "Successful"
          emoji: ":white_check_mark:"
      - notify-slack:
          event_type: "fail"
          success_failed: "failed"
          emoji: ":x:"
workflows:
  deploy_staging:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only: 
               - development
