apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vs-uc-api.fullname" . }}
  labels:
    {{- include "vs-uc-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo 
